import type {CatalogEntry,FishProfile} from "./catalog-types.ts";

export const FISH_SPECIES=["neon-tetra","ember-tetra","cardinal-tetra","green-neon-tetra","black-neon-tetra","glowlight-tetra","rummy-nose-tetra","harlequin-rasbora","chili-rasbora","celestial-pearl-danio","endler-livebearer"] as const;
export type FishSpecies=(typeof FISH_SPECIES)[number];

type Definition={id:FishSpecies;label:string;scientificName:string;length:readonly[number,number];school:readonly[number,number];tempo:number;body:"tetra"|"deep"|"micro"|"danio"|"livebearer";colors:readonly[string,string,string];source:string;publisher:string;traits:readonly string[]};
const definitions:readonly Definition[]=[
  {id:"neon-tetra",label:"Neon Tetra",scientificName:"Paracheirodon innesi",length:[3,4],school:[6,12],tempo:1,body:"tetra",colors:["#4ca8d9","#1a7cc0","#d94e58"],source:"https://www.fishbase.se/summary/Paracheirodon-innesi.html",publisher:"FishBase",traits:["electric blue side band","red rear half","slender characin"]},
  {id:"ember-tetra",label:"Ember Tetra",scientificName:"Hyphessobrycon amandae",length:[1.5,2.5],school:[8,12],tempo:1.18,body:"micro",colors:["#e97931","#a93a19","#f2b34f"],source:"https://www.fishbase.se/summary/Hyphessobrycon-amandae.html",publisher:"FishBase",traits:["warm amber body","small rounded fins","tiny characin"]},
  {id:"cardinal-tetra",label:"Cardinal Tetra",scientificName:"Paracheirodon axelrodi",length:[3,5],school:[6,12],tempo:.9,body:"tetra",colors:["#6697cb","#177fd1","#e33240"],source:"https://www.fishbase.se/summary/Paracheirodon-axelrodi.html",publisher:"FishBase",traits:["blue lateral band","full red underside","slender characin"]},
  {id:"green-neon-tetra",label:"Green Neon Tetra",scientificName:"Paracheirodon simulans",length:[2,3],school:[8,12],tempo:1.1,body:"micro",colors:["#7fae90","#37c8ab","#345b64"],source:"https://www.fishbase.se/summary/Paracheirodon-simulans",publisher:"FishBase",traits:["green iridescent stripe","blue-grey rear","micro characin"]},
  {id:"black-neon-tetra",label:"Black Neon Tetra",scientificName:"Hyphessobrycon herbertaxelrodi",length:[3,4],school:[6,12],tempo:.94,body:"tetra",colors:["#929da1","#202c33","#e6d76e"],source:"https://www.fishbase.se/summary/Hyphessobrycon-herbertaxelrodi.html",publisher:"FishBase",traits:["black lateral stripe","pale upper glow","slender characin"]},
  {id:"glowlight-tetra",label:"Glowlight Tetra",scientificName:"Hemigrammus erythrozonus",length:[3,4],school:[6,12],tempo:1.02,body:"tetra",colors:["#c8b19a","#e4764f","#e5c98b"],source:"https://www.fws.gov/sites/default/files/documents/Ecological-Risk-Screening-Summary-Glowlight-Tetra.pdf",publisher:"U.S. Fish & Wildlife Service",traits:["orange-red side line","translucent fins","slender characin"]},
  {id:"rummy-nose-tetra",label:"Rummy-nose Tetra",scientificName:"Petitella bleheri",length:[3,5],school:[6,12],tempo:1.15,body:"tetra",colors:["#d5d5cd","#cc3540","#1d1d24"],source:"https://www.fishbase.se/summary/Petitella-bleheri.html",publisher:"FishBase",traits:["red head","silver body","striped caudal fin"]},
  {id:"harlequin-rasbora",label:"Harlequin Rasbora",scientificName:"Trigonostigma heteromorpha",length:[3.5,5],school:[6,12],tempo:.82,body:"deep",colors:["#d28655","#402932","#d9a56c"],source:"https://www.fishbase.se/summary/Trigonostigma-heteromorpha.html",publisher:"FishBase",traits:["deep copper body","black wedge patch","tall dorsal fin"]},
  {id:"chili-rasbora",label:"Chili Rasbora",scientificName:"Boraras brigittae",length:[1.3,2],school:[8,12],tempo:1.25,body:"micro",colors:["#d74432","#301d23","#f48649"],source:"https://fishbase.se/summary/Boraras-brigittae",publisher:"FishBase",traits:["red micro body","black lateral stripe","tiny forked tail"]},
  {id:"celestial-pearl-danio",label:"Celestial Pearl Danio",scientificName:"Danio margaritatus",length:[2,2.5],school:[6,12],tempo:1.06,body:"danio",colors:["#253b56","#f4e3a1","#d54b45"],source:"https://www.fishbase.se/summary/Danio-margaritatus.html",publisher:"FishBase",traits:["pearl-spotted blue body","red fins","compact danio"]},
  {id:"endler-livebearer",label:"Endler's Livebearer",scientificName:"Poecilia wingei",length:[2,4],school:[6,12],tempo:1.38,body:"livebearer",colors:["#3b9a74","#e89a30","#181b25"],source:"https://www.fishbase.se/summary/Poecilia-wingei.html",publisher:"FishBase",traits:["slender livebearer body","orange-green patches","fan tail"]},
] as const;

const envelopeByBody:Record<Definition["body"],FishProfile["envelope"]>={tetra:{length:.58,width:.42,height:.28},deep:{length:.6,width:.47,height:.36},micro:{length:.56,width:.38,height:.25},danio:{length:.58,width:.39,height:.27},livebearer:{length:.62,width:.48,height:.32}};
export const fishDefinitionById=new Map(definitions.map(definition=>[definition.id,definition]));
export const fishProfileById=new Map<FishSpecies,FishProfile>(definitions.map(definition=>[definition.id,{type:"fish",scientificName:definition.scientificName,adultLengthCm:definition.length,envelope:envelopeByBody[definition.body],schoolSize:definition.school,swimTempo:definition.tempo,model:definition.id}]));
export const fishCatalogEntries:CatalogEntry[]=definitions.map(definition=>({id:`fish-${definition.id}`,displayLabel:definition.label,kind:"fish",browseTags:["fish",...definition.traits,`${definition.length[0]}–${definition.length[1]} cm`],placementRole:"animated open-water school",rendererForm:definition.body,status:"supported_procedural",source:{url:definition.source,publisher:definition.publisher},identityCaveat:`Species label follows ${definition.publisher}; this original animated model is a visual approximation.`,renderingLimit:"Original animated species model with a conservative swimming envelope; colour and morphology are illustrative.",color:definition.colors[0],fish:fishProfileById.get(definition.id)!}));
export function fishSpeciesFromCatalogId(id:string):FishSpecies|undefined {return id.startsWith("fish-")&&fishDefinitionById.has(id.slice(5) as FishSpecies)?id.slice(5) as FishSpecies:undefined;}
export function fishVisual(id:FishSpecies) {return fishDefinitionById.get(id)!;}
