import type {CatalogEntry,FilterProfile,LightProfile,OrganicCatalogKind,OrganicProfile,SubstrateProfile} from "./catalog-types.ts";

export const expandedOrganicProfiles:Record<string,OrganicProfile>={
  "wood-bogwood":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"supplier-piece",morphology:["waterlogged","stout trunk","broken branches"]},
  "wood-mangrove-root":{type:"organic",nominalSizeCm:[20,50],scaleBasis:"supplier-piece",morphology:["buttress roots","dense root fan","thick forks"]},
  "wood-desert-roots":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"supplier-piece",morphology:["pale surface","fine root fan","open branching"]},
  "wood-wio-sinking":{type:"organic",nominalSizeCm:[10,30],scaleBasis:"supplier-piece",morphology:["compact","gnarled","low centre of mass"]},
  "wood-wio-neptune":{type:"organic",nominalSizeCm:[15,45],scaleBasis:"supplier-piece",morphology:["smooth","pale","directional branches"]},
  "wood-wio-dragonscale":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"supplier-piece",morphology:["eroded cavities","bark ridges","thick core"]},
  "wood-wio-petite":{type:"organic",nominalSizeCm:[8,20],scaleBasis:"supplier-piece",morphology:["nano scale","fine forks","open root fan"]},
  "wood-wio-stone":{type:"organic",nominalSizeCm:[10,30],scaleBasis:"supplier-piece",morphology:["knotted lobes","dense core","short roots"]},
  "wood-wio-elder":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"supplier-piece",morphology:["dark roots","slender whips","flexible spread"]},
  "wood-wio-striped":{type:"organic",nominalSizeCm:[15,45],scaleBasis:"supplier-piece",morphology:["long grain ridges","flowing trunk","tapered forks"]},
  "rock-dragon-stone":{type:"organic",nominalSizeCm:[8,30],scaleBasis:"supplier-piece",morphology:["clay-toned","pitted","layered fissures"]},
  "rock-dragon-peaks":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"supplier-piece",morphology:["tall peak","craggy ridge","narrow footprint"]},
  "rock-elephant-skin":{type:"organic",nominalSizeCm:[10,35],scaleBasis:"supplier-piece",morphology:["folded skin texture","rounded shoulders","pale grey"]},
  "rock-fire-stone":{type:"organic",nominalSizeCm:[8,30],scaleBasis:"supplier-piece",morphology:["warm rust tone","angular facets","broken edges"]},
  "rock-mermaid-rose":{type:"organic",nominalSizeCm:[8,30],scaleBasis:"supplier-piece",morphology:["rose tone","fracture planes","low boulder"]},
  "rock-mountain-stone":{type:"organic",nominalSizeCm:[12,40],scaleBasis:"supplier-piece",morphology:["mountain profile","angular strata","wide base"]},
  "rock-black-river":{type:"organic",nominalSizeCm:[5,25],scaleBasis:"supplier-piece",morphology:["water-rounded","smooth surface","oval boulder"]},
  "rock-black-abyss":{type:"organic",nominalSizeCm:[8,30],scaleBasis:"supplier-piece",morphology:["near-black","irregular mass","sharp contrast"]},
  "rock-blue-mountain":{type:"organic",nominalSizeCm:[10,35],scaleBasis:"supplier-piece",morphology:["blue-grey","horizontal strata","ridge profile"]},
  "rock-wio-midnight":{type:"organic",nominalSizeCm:[8,30],scaleBasis:"supplier-piece",morphology:["vesicular pores","lava texture","near-black"]},
  "rock-ryuoh-stone":{type:"organic",nominalSizeCm:[8,35],scaleBasis:"supplier-piece",morphology:["blue-grey tone","pale calcite seams","jagged stratification"]},
  "plant-rotala-rotundifolia":{type:"organic",nominalSizeCm:[15,30],scaleBasis:"mature-growth",morphology:["opposite leaves","round emersed leaf cue","upright stems"]},
  "plant-rotala-hra":{type:"organic",nominalSizeCm:[20,50],scaleBasis:"mature-growth",morphology:["narrow leaves","arching stems","orange-red tips"]},
  "plant-ludwigia-super-red":{type:"organic",nominalSizeCm:[20,50],scaleBasis:"mature-growth",morphology:["broad opposite leaves","dense stem bush","red foliage"]},
  "plant-hygrophila-pinnatifida":{type:"organic",nominalSizeCm:[10,40],scaleBasis:"mature-growth",morphology:["deeply lobed leaves","creeping shoots","hardscape attachment"]},
  "plant-staurogyne-repens":{type:"organic",nominalSizeCm:[3,10],scaleBasis:"mature-growth",morphology:["compact opposite leaves","creeping stems","bushy foreground"]},
  "plant-limnophila-sessiliflora":{type:"organic",nominalSizeCm:[15,40],scaleBasis:"mature-growth",morphology:["feathery whorls","fine divided leaves","upright stems"]},
  "plant-pogostemon-helferi":{type:"organic",nominalSizeCm:[5,10],scaleBasis:"mature-growth",morphology:["compact rosette","strongly waved margins","star-shaped crown"]},
  "plant-helanthium-tenellum":{type:"organic",nominalSizeCm:[5,15],scaleBasis:"mature-growth",morphology:["short ribbon leaves","runners","foreground lawn"]},
  "plant-vallisneria-nana":{type:"organic",nominalSizeCm:[30,80],scaleBasis:"mature-growth",morphology:["long narrow ribbons","basal rosette","runners"]},
  "plant-taxiphyllum-barbieri":{type:"organic",nominalSizeCm:[3,10],scaleBasis:"mature-growth",morphology:["irregular branching","small lateral leaves","attached mat"]},
  "plant-echinodorus-bleherae":{type:"organic",nominalSizeCm:[20,50],scaleBasis:"mature-growth",morphology:["broad lanceolate leaves","strong midrib","large basal rosette"]},
  "plant-microsorum-pteropus":{type:"organic",nominalSizeCm:[15,30],scaleBasis:"mature-growth",morphology:["creeping rhizome","wavy strap fronds","hardscape attachment"]},
  "plant-cabomba-caroliniana":{type:"organic",nominalSizeCm:[30,80],scaleBasis:"mature-growth",morphology:["fan-shaped divided leaves","dense rounded whorls","upright stems"]},
  "plant-sagittaria-subulata":{type:"organic",nominalSizeCm:[5,30],scaleBasis:"mature-growth",morphology:["tapered ribbon leaves","basal rosette","spreading runners"]},
};

const natural=(kind:OrganicCatalogKind,id:string,label:string,form:string,color:string,role:string,tags:string[],publisher:string,url:string,identity:string):CatalogEntry=>({
  id,displayLabel:label,kind,browseTags:tags,placementRole:role,rendererForm:form,status:"supported_procedural",color,
  source:{publisher,url},identityCaveat:identity,
  renderingLimit:"A detailed, deterministic procedural counterpart. It is not a scan of an individual natural specimen or supplier product.",
  organic:expandedOrganicProfiles[id],
});

const substrate=(id:string,label:string,color:string,grain:string,depth:number,roughness:number,publisher:string,url:string):CatalogEntry=>({
  id,displayLabel:label,kind:"substrate",browseTags:["substrate",grain,"floor layer"],placementRole:"tank-wide floor profile",rendererForm:"substrate",status:"supported_procedural",color,
  source:{publisher,url},identityCaveat:"Product identity and grain description follow the linked manufacturer source; the preview is an original procedural terrain.",
  renderingLimit:"Procedural floor profile with representative grain scale and colour; it is not manufacturer photography or a chemical water-parameter simulation.",
  system:{type:"substrate",grain,depth,roughness} satisfies SubstrateProfile,
});

const filter=(id:string,label:string,color:string,mount:"rear"|"rim"|"internal",silhouette:"canister"|"hob"|"internal",flowClass:FilterProfile["flowClass"],flowStrength:number,outlet:FilterProfile["outlet"],nominalDimensionsCm:FilterProfile["nominalDimensionsCm"],ratedFlowLph:number,compatibleVolumeLitres:FilterProfile["compatibleVolumeLitres"],publisher:string,url:string):CatalogEntry=>({
  id,displayLabel:label,kind:"filter",browseTags:["filter",silhouette,flowClass.toLowerCase(),"water movement"],placementRole:mount==="rim"?"rear-rim mounted return":mount==="internal"?"rear-corner internal filter":"rear-mounted intake and return",rendererForm:silhouette,status:"supported_procedural",color,
  source:{publisher,url},identityCaveat:"Dimensions, fit band, pump output, and mounting follow the linked manufacturer source. The hoses are a procedural installation path, not a bespoke plumbing plan.",
  renderingLimit:"A rigid, dimensioned procedural housing, intake, and return. Fishy bounds the source-listed pump output into a stable visual water model rather than certifying performance.",
  system:{type:"filter",mount,silhouette,flowClass,flowStrength,outlet,nominalDimensionsCm,ratedFlowLph,compatibleVolumeLitres} satisfies FilterProfile,
});

const light=(id:string,label:string,color:string,mount:"rim"|"suspended",silhouette:"bar"|"pendant",kelvin:number,intensity:number,beam:number,nominalDimensionsCm:LightProfile["nominalDimensionsCm"],compatibleTankWidthCm:LightProfile["compatibleTankWidthCm"],ratedWatts:number,publisher:string,url:string):CatalogEntry=>({
  id,displayLabel:label,kind:"light",browseTags:["light",silhouette,kelvin+"K","planted tank"],placementRole:mount==="rim"?"level rim-mounted fixture":"centred suspended fixture",rendererForm:silhouette,status:"supported_procedural",color,
  source:{publisher,url},identityCaveat:"Dimensions, supported span, wattage, and mounting follow the linked manufacturer source. Kelvin and output in Fishy remain bounded visual simulation targets, not a spectral measurement.",
  renderingLimit:"A rigid, dimensioned procedural fixture whose emitted light controls the browser renderer; it is not a manufacturer photometric simulation.",
  system:{type:"light",mount,silhouette,kelvin,intensity,beam,nominalDimensionsCm,compatibleTankWidthCm,ratedWatts} satisfies LightProfile,
});

export const catalogExpansion:CatalogEntry[]=[
  natural("wood","wood-bogwood","Tropica Bogwood","stump","#4b3325","low, waterlogged branch foundation",["dark","root","anchored"],"Tropica","https://tropica.com/en/plants/aquadecor/bogwood/","Bogwood is a natural material with variable branching and tannin release."),
  natural("wood","wood-mangrove-root","Mangrove Root","root","#735039","thick focal root with anchored contact",["root","dense","focal"],"Tropica","https://tropica.com/en/inspiration/layout/Layout27/4963","Mangrove-root silhouette is representative; individual roots vary in density and curvature."),
  natural("wood","wood-desert-roots","Desert Wood Roots","spider","#b99a72","fine aerial-root canopy",["fine branches","pale","canopy"],"Tropica","https://tropica.com/en/inspiration/layout/layout29/4973","A layout-material counterpart, not a claim about any supplied specimen."),
  natural("wood","wood-wio-sinking","WIO Sinking Wood","stump","#7b5131","compact, gnarled floor anchor",["gnarled","dense","floor"],"WIO","https://www.wio.eco/product/sinking-wood","The product name is retained as a real-world counterpart; the model is a procedural approximation."),
  natural("wood","wood-wio-neptune","WIO Neptune Wood","root","#c1aa83","smooth pale directional driftwood",["pale","smooth","directional"],"WIO","https://www.wio.eco/product/neptune-wood","Natural weathering makes exact tone and branch spread variable."),
  natural("wood","wood-wio-dragonscale","WIO Dragonscale Wood","stump","#85552f","perforated, bark-ridged focal wood",["cavities","ridged","texture"],"WIO","https://www.wio.eco/product/dragonscale-wood","The rendered cavity pattern is representative rather than a specimen scan."),
  natural("wood","wood-wio-petite","WIO Petite Wood","spider","#ad895a","nano branching accent",["nano","sandblasted","branch"],"WIO","https://www.wio.eco/product/petite-wood","Small natural pieces vary in fork count and thickness."),
  natural("wood","wood-wio-stone","WIO Stone Wood","stump","#89613b","bumpy dense root-rock hybrid",["dense","bumpy","anchor"],"WIO","https://www.wio.eco/product/stone-wood","The name describes a product style; no mineral composition is implied."),
  natural("wood","wood-wio-elder","WIO Elder Root","root","#4d3428","dark flexible root mass",["dark","root mass","tannin"],"WIO","https://www.wio.eco/product/elder-root","Natural grain and root spread are variable."),
  natural("wood","wood-wio-striped","WIO Striped Wood","angular","#a67549","flowing striped branch structure",["striped","flowing","branch"],"WIO","https://www.wio.eco/product/striped-wood","The stripe and branch pattern are rendered cues, not a source texture."),

  natural("rock","rock-dragon-stone","CaribSea Dragon Stone","porous","#9b7a51","porous layered hardscape focal",["porous","ochre","layered"],"CaribSea","https://caribsea.com/freshwater-substrates/","Natural stone size, mineral mix, and fissures vary piece to piece."),
  natural("rock","rock-dragon-peaks","CaribSea Dragon Stone Peaks","crag","#8d765c","tall craggy ridge",["crag","ridge","heavy"],"CaribSea","https://caribsea.com/freshwater-substrates/","A dimensional proxy for a heavy floor-supported rock formation."),
  natural("rock","rock-elephant-skin","CaribSea Elephant Skin Rock","weathered","#9c9a91","weathered folded midground stone",["folded","pale","weathered"],"CaribSea","https://caribsea.com/freshwater-substrates/","Surface folds are procedural counterparts, not exact mineral strata."),
  natural("rock","rock-fire-stone","CaribSea Fire Stones","faceted","#9b5840","warm faceted accent boulder",["rust","faceted","accent"],"CaribSea","https://caribsea.com/freshwater-substrates/","Natural iron-rich colour can differ between pieces."),
  natural("rock","rock-mermaid-rose","CaribSea Mermaid Rose Stone","fractured","#a77873","rose fractured accent stone",["rose","fractured","accent"],"CaribSea","https://caribsea.com/freshwater-substrates/","Colour is a representative visual cue rather than a water-chemistry claim."),
  natural("rock","rock-mountain-stone","CaribSea Mountain Stone","mountain","#6f7474","angular mountain foundation",["grey","angular","foundation"],"CaribSea","https://caribsea.com/freshwater-substrates/","The model is intended for floor-supported aquascape placement."),
  natural("rock","rock-black-river","CaribSea Black River Rock","rounded","#2f3534","smooth rounded river boulder",["smooth","dark","rounded"],"CaribSea","https://caribsea.com/freshwater-substrates/","Rounded silhouette is a representative erosion profile."),
  natural("rock","rock-black-abyss","CaribSea Black Abyss Stone","basalt","#252b2e","near-black irregular contrast rock",["black","irregular","contrast"],"CaribSea","https://caribsea.com/freshwater-substrates/","The visual name does not imply a tested geological classification."),
  natural("rock","rock-blue-mountain","CaribSea Blue Mountain Stone","stratified","#596e7d","blue-grey stratified ridge stone",["blue-grey","strata","ridge"],"CaribSea","https://caribsea.com/freshwater-substrates/","Strata direction and edge weathering are procedural."),
  natural("rock","rock-wio-midnight","WIO Midnight Stone","vesicular","#242529","jet-black porous lava hardscape",["lava","porous","midnight"],"WIO","https://www.wio.eco/product/midnight-stone-kit","The counterpart is a natural porous rock; individual cavities vary."),
  natural("rock","rock-ryuoh-stone","WIO Ryuoh Stone","stratified","#6d7474","jagged blue-grey ridge with pale seams",["ryuoh","jagged","seamed"],"WIO","https://www.wio.eco/product/ryuoh-gravel","Natural seam placement and fracture profiles vary by piece."),

  natural("plant","plant-rotala-rotundifolia","Rotala rotundifolia","stem","#6d9a53","fine background stem grouping",["stem","green-red","background"],"Tropica","https://tropica.com/en/plants/plantdetails/Rotalarotundifolia%28033%29/4447","Growth colour changes with cultivation and light; the preview is a morphology cue."),
  natural("plant","plant-rotala-hra","Rotala h'ra","stem","#c35c47","warm red stem accent",["stem","red","accent"],"Tropica","https://tropica.com/en/plants/","Trade-name and colour response follow grow conditions, not a colour guarantee."),
  natural("plant","plant-ludwigia-super-red","Ludwigia palustris 'Super Red'","stem","#b83f45","dense red background stem group",["stem","red","background"],"Tropica","https://tropica.com/en/plants/plant-clips/","Cultivar colour is strongly environment-dependent."),
  natural("plant","plant-hygrophila-pinnatifida","Hygrophila pinnatifida","fern","#5d7a47","lobed hardscape-mounted foliage",["lobed","midground","epiphyte"],"Tropica","https://tropica.com/en/plants/","The model represents a mounted foliage habit, not a care schedule."),
  natural("plant","plant-staurogyne-repens","Staurogyne repens","broadleaf","#52754a","low bushy midground clump",["bushy","low","midground"],"Tropica","https://tropica.com/en/plants/","Plant stature varies with trimming and nutrient conditions."),
  natural("plant","plant-limnophila-sessiliflora","Limnophila sessiliflora","stem","#6a9a60","feathery background stem grove",["feathery","stem","background"],"Tropica","https://tropica.com/en/plants/plant-clips/","The whorled foliage is a procedural counterpart, not a live growth simulation."),
  natural("plant","plant-pogostemon-helferi","Pogostemon helferi","broadleaf","#648452","curled rosette accent",["rosette","curled","accent"],"Tropica","https://tropica.com/en/plants/","Leaf curl and colour are representative."),
  natural("plant","plant-helanthium-tenellum","Helanthium tenellum","grass","#78975a","short grassy foreground",["grass","foreground","runner"],"Tropica","https://tropica.com/en/plants/","The preview represents a planted clump rather than a spread rate."),
  natural("plant","plant-vallisneria-nana","Vallisneria nana","grass","#557e4a","long ribbon-leaf background",["ribbon","grass","background"],"Tropica","https://tropica.com/en/plants/","Leaf length depends on tank depth and cultivation."),
  natural("plant","plant-taxiphyllum-barbieri","Taxiphyllum barbieri","moss","#4c7d43","irregular Java moss attachment",["moss","attachment","texture"],"Tropica","https://tropica.com/en/plants/","Common-name moss morphology varies with flow and trimming."),
  natural("plant","plant-echinodorus-bleherae","Echinodorus 'Bleherae'","broadleaf","#4f8244","large broadleaf background rosette",["amazon sword","broadleaf","background"],"Tropica","https://tropica.com/en/plants/plantdetails/Echinodorus%27Bleherae%27%28071%29/4512","Leaf stature depends on aquarium size, nutrition, and pruning."),
  natural("plant","plant-microsorum-pteropus","Microsorum pteropus","fern","#46733c","rhizome-mounted Java fern",["java fern","epiphyte","wavy"],"Tropica","https://tropica.com/en/plants/","Frond shape is a representative mature-growth cue."),
  natural("plant","plant-cabomba-caroliniana","Cabomba caroliniana","stem","#70a64f","dense rounded feathery background mass",["cabomba","feathery","whorl"],"Tropica","https://tropica.com/en/plants/","The procedural whorls represent the plant's fine divided foliage rather than every leaflet."),
  natural("plant","plant-sagittaria-subulata","Sagittaria subulata","grass","#719653","runner-spreading ribbon foreground",["sagittaria","runner","ribbon"],"Tropica","https://tropica.com/en/plants/plantdetails/4530/4530","Leaf height and runner density vary with light and trimming."),

  substrate("substrate-ada-amazonia-v2","ADA Aqua Soil Amazonia Ver.2","#3a332c","dark porous granules",.045,.94,"ADA","https://www.adana.co.jp/en/release/detail?id=771"),
  substrate("substrate-ada-amazonia-powder","ADA Aqua Soil Amazonia Ver.2 Powder","#302b27","fine dark granules",.035,.92,"ADA","https://www.adana.co.jp/jp/contents/products/na_substrate/detail02.html"),
  substrate("substrate-ada-amazonia-pro","ADA Amazonia PRO","#24221f","nutrient-soil pellets",.05,.95,"ADA","https://www.adana.co.jp/en/release/detail?id=1570"),
  substrate("substrate-fluval-stratum","Fluval Stratum","#3f3930","volcanic soil pellets",.045,.9,"Fluval","https://fluvalaquatics.com/uk/shop/product/stratum-series-page"),
  substrate("substrate-fluval-bio-stratum","Fluval Bio-Stratum","#332f2b","porous planted-soil granules",.045,.92,"Fluval","https://fluvalaquatics.com/uk/shop/product/stratum-series-page"),
  substrate("substrate-fluval-betta-stratum","Fluval Betta Stratum","#39332c","fine nano-soil granules",.03,.91,"Fluval","https://fluvalaquatics.com/uk/shop/product/stratum-series-page"),
  substrate("substrate-seachem-flourite","Seachem Flourite","#744b36","porous clay gravel",.045,.96,"Seachem","https://ftp.seachem.com/flourite.php"),
  substrate("substrate-seachem-flourite-black","Seachem Flourite Black","#282a28","charcoal clay gravel",.045,.96,"Seachem","https://ftp.seachem.com/flourite.php"),
  substrate("substrate-caribsea-eco-black","CaribSea Eco-Planted Black","#272827","black basaltic grains",.04,.94,"CaribSea","https://caribsea.com/freshwater-substrates/"),
  substrate("substrate-caribsea-eco-red","CaribSea Eco-Planted Red","#7a3f30","red laterite gravel",.04,.93,"CaribSea","https://caribsea.com/freshwater-substrates/"),
  substrate("substrate-ada-la-plata-sand","ADA La Plata Sand","#c7b17e","natural fine sand with mixed grains",.032,.88,"ADA","https://www.adana.co.jp/en/contents/products/na_substrate/detail03.html"),
  substrate("substrate-caribsea-peace-river","CaribSea Peace River","#a98b61","small smooth river gravel",.035,.9,"CaribSea","https://caribsea.com/freshwater-substrates/"),

  filter("filter-oase-biomaster-150","Oase BioMaster² Thermo 150","#333b3a","rear","canister","Moderate",.42,"jet",[24,24,31.5],850,[0,150],"Oase","https://www.oase.com/en-US/aquarium/biomaster-thermo-150"),
  filter("filter-oase-biomaster-250","Oase BioMaster² Thermo 250","#35413d","rear","canister","Moderate",.5,"jet",[24,24,37],900,[0,250],"Oase","https://www.oase.com/en/aquarium/biomaster-thermo-250-gb"),
  filter("filter-oase-biomaster-350","Oase BioMaster² Thermo 350","#2d3a35","rear","canister","High",.64,"jet",[24,24,42.5],1100,[0,350],"Oase","https://www.oase.com/en/aquarium/biomaster-thermo-350-gb"),
  filter("filter-fluval-107","Fluval 107 Canister Filter","#31363d","rear","canister","Gentle",.34,"jet",[19,18,35],550,[40,130],"Fluval","https://fluvalaquatics.com/ca/shop/product/107-canister-filter"),
  filter("filter-fluval-207","Fluval 207 Canister Filter","#30363c","rear","canister","Moderate",.47,"jet",[19,18,42],780,[60,220],"Fluval","https://fluvalaquatics.com/us/shop/product/207-canister-filter-20-45-us-gal-60-220-l"),
  filter("filter-fluval-307","Fluval 307 Canister Filter","#30363c","rear","canister","High",.58,"line",[24,18,42],1150,[90,330],"Fluval","https://fluvalaquatics.com/us/shop/product/307-canister-filter-40-70-us-gal-90-330-l"),
  filter("filter-fluval-407","Fluval 407 Canister Filter","#252d34","rear","canister","High",.72,"line",[24,18,49],1450,[150,500],"Fluval","https://fluvalaquatics.com/us/shop/product/407-canister-filter-50-100-us-gal-150-500-l"),
  filter("filter-eheim-classic-250","Eheim classic 250","#34684b","rear","canister","Gentle",.32,"line",[16,16,35.5],440,[80,250],"Eheim","https://eheim.com/media/3e/b6/2a/1737110772/EHEIM_Haendlerkatalog_EN_0923.pdf"),
  filter("filter-seachem-tidal-35","Seachem Tidal 35","#283238","rim","hob","Moderate",.45,"sheet",[15.5,13,18],500,[0,130],"Seachem","https://www.seachem.com/tidal-compare.php"),
  filter("filter-seachem-tidal-55","Seachem Tidal 55","#253138","rim","hob","High",.6,"sheet",[20.5,15.5,21.4],1000,[0,200],"Seachem","https://www.seachem.com/tidal-compare.php"),
  filter("filter-oase-bioplus-thermo-100","Oase BioPlus Thermo 100","#2e3937","internal","internal","Moderate",.46,"line",[12,11,27],500,[0,100],"Oase","https://www.oase.com/en-US/aquarium/bioplus-thermo-100"),

  light("light-ada-solar-rgb-ii","ADA Solar RGB II","#25282b","suspended","pendant",7000,.78,.9,[43,28,6.4],[60,90],135,"ADA","https://www.adana.co.jp/en/contents/products/na_lighting/detail05.html"),
  {...light("light-ada-aquasky-rgb-ii-60","ADA AQUASKY RGB II 60","#282d31","rim","bar",9500,.66,.82,[60,13,13],[60,60],108,"ADA","https://www.adana.co.jp/jp/contents/products/na_lighting/aquasky_rgb2/index.html"),browseTags:["light","bar","8000–11000K default CCT","108W rated power","0–66W consumption","planted tank"],identityCaveat:"ADA lists an approximately 8,000–11,000 K default-mode range, 108 W rated power, and 0–66 W power consumption. Fishy uses the 9,500 K midpoint and 66% normalized visual intensity as bounded rendering inputs, not electrical or spectral measurements."},
  light("light-fluval-plant-22","Fluval Plant 3.0 22 W","#2d3236","rim","bar",6500,.5,.72,[38,6.4,2],[38,61],22,"Fluval","https://fluvalaquatics.com/us/shop/product/plant-3-0"),
  light("light-fluval-plant-32","Fluval Plant 3.0 32 W","#2d3236","rim","bar",6500,.6,.76,[61,6.4,2],[61,85],32,"Fluval","https://fluvalaquatics.com/us/shop/product/plant-3-0"),
  light("light-fluval-plant-46","Fluval Plant 3.0 46 W","#2d3236","rim","bar",6500,.72,.82,[91.5,6.4,2],[91,115],46,"Fluval","https://fluvalaquatics.com/us/shop/product/plant-3-0"),
  light("light-fluval-plant-59","Fluval Plant 3.0 59 W","#2d3236","rim","bar",6500,.84,.88,[122,6.4,2],[122,153],59,"Fluval","https://fluvalaquatics.com/us/shop/product/plant-3-0"),
  light("light-fluval-aquasky-12","Fluval Aquasky 3.0 12 W","#2b343c","rim","bar",6800,.42,.68,[38,6.4,2],[38,63],12,"Fluval","https://fluvalaquatics.com/us/shop/product/aquasky-3-0-led-12w-15-24-5-38-63-cm"),
  light("light-fluval-aquasky-18","Fluval Aquasky 3.0 18 W","#2b343c","rim","bar",6800,.5,.72,[61,6.4,2],[61,93],18,"Fluval","https://fluvalaquatics.com/us/shop/product/aquasky-3-0-led-18w-24-25-36-5-61-93-cm"),
  light("light-fluval-aquasky-27","Fluval Aquasky 3.0 27 W","#2b343c","rim","bar",6800,.6,.78,[91,6.4,2],[91,123],27,"Fluval","https://fluvalaquatics.com/us/shop/product/aquasky-3-0-led-27w-36-48-25-91-123-cm"),
  light("light-fluval-aquasky-35","Fluval Aquasky 3.0 35 W","#2b343c","rim","bar",6800,.72,.84,[123,6.4,2],[123,154],35,"Fluval","https://fluvalaquatics.com/us/shop/product/aquasky-3-0-led-35w-48-25-60-5-123-154-cm"),
];
