"""Bake a compact surface proxy from the actual delivered stone for cascade contact.
This is geometric contact data, not a replacement for the detailed visible GLB.
"""
import bpy,os,json
from mathutils import Vector
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
bpy.ops.import_scene.gltf(disable_bone_shape=True,filepath=ROOT+'/site/public/render-assets/models/rock-rounded.glb')
objects=[o for o in bpy.context.scene.objects if o.type=='MESH']
points=[o.matrix_world@v.co for o in objects for v in o.data.vertices]
def yup(p):return (p.x,p.z,-p.y)
lo=[min(yup(p)[i] for p in points) for i in range(3)];hi=[max(yup(p)[i] for p in points) for i in range(3)]
positions=[];indices=[]
for o in objects:
 bpy.ops.object.select_all(action='DESELECT');o.select_set(True);bpy.context.view_layer.objects.active=o
 dec=o.modifiers.new('Contact surface reduction','DECIMATE');dec.ratio=.075;bpy.ops.object.modifier_apply(modifier=dec.name)
 mesh=o.data;mesh.calc_loop_triangles();offset=len(positions)//3
 for v in mesh.vertices:positions.extend([round(f,6) for f in yup(o.matrix_world@v.co)])
 for tri in mesh.loop_triangles:indices.extend([offset+i for i in tri.vertices])
record={'min':lo,'max':hi,'positions':positions,'indices':indices}
# TS keeps the data import synchronous in the browser and the Node reference exporter.
with open(ROOT+'/site/lib/rock-contact-surface.ts','w') as out:
 out.write('// Generated by blender/export_contact_surface.py from rock-rounded.glb.\n')
 out.write('export const rockContactSurface='+json.dumps(record,separators=(',',':'))+';\n')
print('CONTACT_SURFACE',len(positions)//3,'vertices',len(indices)//3,'triangles')
