"use client";
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from "react";
import * as T from "three";
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls.js";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Slider} from "@/components/ui/slider";
import {makeObject,disposeObject,tankBounds} from "@/lib/geometry";
import {createAquariumStage} from "@/lib/aquarium-stage";
import {createSculpt,brushSculpt,minimumBrushRadius,type Sculpt,type BrushMode} from "@/lib/sculpt";
import type {SceneObject,SceneRecord} from "@/lib/scene";

type Props={scene:SceneRecord;object:SceneObject;onApply:(sculpt:Sculpt|undefined,base:number)=>boolean;onClose:()=>void;onDraft:(pending:boolean)=>void};
export function SculptEditor({scene,object,onApply,onClose,onDraft}:Props) {
  const initial=useMemo(()=>{if(object.sculpt)return structuredClone(object.sculpt);const g=makeObject({...object,sculpt:undefined,position:[0,0,0],rotation:[0,0,0],size:1,stretch:[1,1,1]});try{return createSculpt(g,{kind:object.kind,form:object.form});}finally{disposeObject(g);}},[object]);
  const fields=useRef(initial),history=useRef<Sculpt[]>([]),[revision,setRevision]=useState(0),[mode,setMode]=useState<BrushMode|"orbit">("pull"),[radius,setRadius]=useState(4),[strength,setStrength]=useState(1),[message,setMessage]=useState("Drag on the surface to reshape it."),[error,setError]=useState(""),[dimensions,setDimensions]=useState(""),host=useRef<HTMLDivElement>(null),reset=useRef<(()=>void)|null>(null),rebuild=useRef<((value:Sculpt)=>boolean)|null>(null),params=useRef({mode,radius,strength});useLayoutEffect(()=>{params.current={mode,radius,strength};},[mode,radius,strength]);
  const [draftSnapshot,setDraftSnapshot]=useState(initial),[historyCount,setHistoryCount]=useState(0);
  const changed=JSON.stringify(draftSnapshot)!==JSON.stringify(initial);
  const [canvasHost,setCanvasHost]=useState<HTMLDivElement|null>(null);
  const cancelActive=useRef<(()=>boolean)|null>(null);
  const opener=useRef(typeof document!=="undefined"?document.activeElement as HTMLElement|null:null);
  const [minimumRadius,setMinimumRadius]=useState(.2),radiusFloor=useRef(.002);
  useEffect(()=>{onDraft(true);return()=>onDraft(false);},[onDraft]);
  useEffect(()=>{if(!canvasHost)return;for(const control of canvasHost.parentElement?.querySelectorAll('[data-slot="slider"][aria-label]')??[]){const name=control.getAttribute("aria-label");if(name)control.querySelector('[role="slider"]')?.setAttribute("aria-label",name);}},[canvasHost]);
  useEffect(()=>{
    const container=canvasHost;if(!container)return;let renderer:T.WebGLRenderer|undefined,controls:OrbitControls|undefined,observer:ResizeObserver|undefined,animation=0,objectMesh:T.Group|undefined,stage:ReturnType<typeof createAquariumStage>|undefined;
    try{
      renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));renderer.domElement.setAttribute("role","img");renderer.domElement.setAttribute("aria-label",`Sculpt ${object.name} surface`);container.appendChild(renderer.domElement);stage=createAquariumStage(renderer);
      const camera=new T.PerspectiveCamera(38,1,.001,40);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.025;controls.maxDistance=10;
      const boundary=tankBounds(scene),wire=new T.Box3Helper(boundary,0x526863);stage.scene.add(wire);
      const cursor=new T.Mesh(new T.RingGeometry(.96,1,64),new T.MeshBasicMaterial({color:0x83ffe1,side:T.DoubleSide,transparent:true,opacity:.9,depthTest:false}));cursor.visible=false;cursor.renderOrder=20;stage.scene.add(cursor);
      const show=(value:Sculpt,check=true)=>{const candidate=makeObject({...object,sculpt:value}),box=new T.Box3().setFromObject(candidate);if(check&&!boundary.containsBox(box)){disposeObject(candidate);setMessage("Tank boundary reached. Stroke limited; the object was not moved.");return false;}if(objectMesh){stage!.scene.remove(objectMesh);disposeObject(objectMesh);}objectMesh=candidate;stage!.scene.add(candidate);radiusFloor.current=minimumBrushRadius(value,candidate.matrixWorld);const cm=Math.ceil(radiusFloor.current*1000)/10;setMinimumRadius(cm);setRadius(previous=>Math.max(previous,cm));const size=box.getSize(new T.Vector3());setDimensions(`${(size.x*100).toFixed(2)} × ${(size.z*100).toFixed(2)} × ${(size.y*100).toFixed(2)} cm`);return true;};
      show(fields.current,false);rebuild.current=value=>{if(!show(value))return false;fields.current=structuredClone(value);setDraftSnapshot(fields.current);setRevision(n=>n+1);return true;};
      reset.current=()=>{const box=new T.Box3().setFromObject(objectMesh!),center=box.getCenter(new T.Vector3()),size=box.getSize(new T.Vector3()).length();camera.position.copy(center).add(new T.Vector3(.7,.45,1).normalize().multiplyScalar(size*1.8));controls!.target.copy(center);controls!.update();};reset.current();
      const ray=new T.Raycaster(),pointer=new T.Vector2();let stroke:Sculpt|null=null,stampAt=0,activePointer:number|null=null;
      const hit=(event:PointerEvent)=>{const rect=renderer!.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);return ray.intersectObject(objectMesh!,true)[0];};
      const point=(event:PointerEvent,stamp:boolean)=>{const contact=hit(event);if(!contact?.face){cursor.visible=false;return;}const normal=contact.face.normal.clone().applyMatrix3(new T.Matrix3().getNormalMatrix(contact.object.matrixWorld)).normalize();if(normal.dot(ray.ray.direction)>0)normal.negate();cursor.visible=params.current.mode!=="orbit";cursor.position.copy(contact.point).addScaledVector(normal,.0003);cursor.scale.setScalar(params.current.radius/100);cursor.quaternion.setFromUnitVectors(new T.Vector3(0,0,1),normal);
        if(!stamp||params.current.mode==="orbit")return;const now=performance.now();if(now-stampAt<45)return;stampAt=now;const result=brushSculpt(fields.current,objectMesh!.matrixWorld,contact.point,normal,Math.max(params.current.radius/100,radiusFloor.current),params.current.strength/1000,params.current.mode);if(result.changed){if(rebuild.current?.(result.sculpt))setMessage("Draft shape updated. Apply to keep it, or Cancel to discard.");}else setMessage(params.current.mode==="smooth"?"No deformation to smooth here.":"No control points reached. Try a larger brush radius.");};
      const down=(event:PointerEvent)=>{if(params.current.mode==="orbit"||event.button!==0||stroke)return;event.preventDefault();event.stopPropagation();if(!hit(event))return;stroke=structuredClone(fields.current);activePointer=event.pointerId;stampAt=0;renderer!.domElement.setPointerCapture(event.pointerId);point(event,true);};
      const move=(event:PointerEvent)=>{if(stroke&&event.pointerId!==activePointer)return;point(event,!!stroke);};
      const up=(event:PointerEvent)=>{if(activePointer!==event.pointerId)return;if(stroke&&JSON.stringify(stroke)!==JSON.stringify(fields.current)){history.current=[...history.current.slice(-19),stroke];setHistoryCount(history.current.length);setRevision(n=>n+1);}stroke=null;activePointer=null;};
      cancelActive.current=()=>{if(!stroke)return false;const original=stroke,pointerId=activePointer;stroke=null;activePointer=null;cursor.visible=false;rebuild.current?.(original);setMessage("Stroke cancelled; previous draft restored.");if(pointerId!==null&&renderer!.domElement.hasPointerCapture(pointerId))renderer!.domElement.releasePointerCapture(pointerId);return true;};
      const cancelStroke=(event:PointerEvent)=>{if(activePointer===event.pointerId)cancelActive.current?.();};
      const leave=()=>{if(!stroke)cursor.visible=false;};
      renderer.domElement.addEventListener("pointerdown",down);renderer.domElement.addEventListener("pointermove",move);renderer.domElement.addEventListener("pointerup",up);renderer.domElement.addEventListener("pointercancel",cancelStroke);renderer.domElement.addEventListener("lostpointercapture",cancelStroke);renderer.domElement.addEventListener("pointerleave",leave);
      const resize=()=>{const w=container.clientWidth,h=container.clientHeight;if(w&&h){camera.aspect=w/h;camera.updateProjectionMatrix();renderer!.setSize(w,h,false);}};observer=new ResizeObserver(resize);observer.observe(container);resize();
      const draw=()=>{controls!.enabled=params.current.mode==="orbit";controls!.update();renderer!.render(stage!.scene,camera);animation=requestAnimationFrame(draw);};draw();
      return()=>{rebuild.current=null;reset.current=null;cancelActive.current=null;cancelAnimationFrame(animation);observer?.disconnect();controls?.dispose();renderer?.domElement.removeEventListener("pointerdown",down);renderer?.domElement.removeEventListener("pointermove",move);renderer?.domElement.removeEventListener("pointerup",up);renderer?.domElement.removeEventListener("pointercancel",cancelStroke);renderer?.domElement.removeEventListener("lostpointercapture",cancelStroke);renderer?.domElement.removeEventListener("pointerleave",leave);disposeObject(stage!.scene);stage?.dispose();renderer?.dispose();renderer?.forceContextLoss();container.replaceChildren();};
    }catch(e){queueMicrotask(()=>setError((e as Error).message||"3D sculpting unavailable."));return()=>{cancelAnimationFrame(animation);observer?.disconnect();controls?.dispose();if(stage){disposeObject(stage.scene);stage.dispose();}renderer?.dispose();container.replaceChildren();};}
  },[object,scene,canvasHost]);
  const undoStroke=()=>{if(cancelActive.current?.())return;const previous=history.current.pop();setHistoryCount(history.current.length);if(previous)rebuild.current?.(previous);};
  return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="sculpt-dialog" data-sculpt-dialog onCloseAutoFocus={e=>{e.preventDefault();if(opener.current?.isConnected&&opener.current.getClientRects().length)opener.current.focus();else document.querySelector<HTMLElement>('[aria-label="Open configuration"]')?.focus();}} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.stopPropagation();undoStroke();}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="s"){e.preventDefault();e.stopPropagation();}}}>
    <DialogTitle>Shape {object.name}</DialogTitle><DialogDescription>Soft sculpting changes the actual surface. Your tank stays unchanged until Apply.</DialogDescription>
    <div className="sculpt-workspace"><div className="sculpt-canvas" ref={setCanvasHost}/><div className="sculpt-tools"><RadioGroup aria-label="Sculpt tool" value={mode} onValueChange={v=>setMode(v as typeof mode)} className="sculpt-modes">{(["pull","push","smooth","orbit"] as const).map(value=><label className="shape-choice" data-selected={mode===value} key={value}><RadioGroupItem value={value}/><span>{value[0].toUpperCase()+value.slice(1)}</span></label>)}</RadioGroup>
    <label>Brush radius <output>{radius.toFixed(1)} cm</output><Slider className="scene-slider" aria-label="Brush radius" min={minimumRadius} max={Math.max(50,minimumRadius+10)} step={.1} value={[radius]} onValueChange={v=>setRadius(v[0])}/><input aria-label="Brush radius in centimetres" type="number" min={minimumRadius} max={Math.max(50,minimumRadius+10)} step={.1} value={radius} onChange={e=>{const n=Number(e.target.value);if(n>=minimumRadius&&n<=Math.max(50,minimumRadius+10))setRadius(n);}}/></label><p className="micro">Minimum brush radius: {minimumRadius.toFixed(1)} cm. Fine brushes use the nearest local deformation control point.</p>
    <label>Strength <output>{strength.toFixed(1)} mm/stamp</output><Slider className="scene-slider" aria-label="Brush strength" min={.1} max={5} step={.1} value={[strength]} onValueChange={v=>setStrength(v[0])}/></label>
    <p>Object W × D × H<br/>{dimensions}</p><p className="micro">Brush units follow the scene scale. Soft deformation, not clay remeshing or a physical measurement.</p><button onClick={()=>reset.current?.()}>Frame object</button><button disabled={!historyCount} onClick={undoStroke}>Undo stroke</button><button onClick={()=>{history.current=[...history.current.slice(-19),structuredClone(fields.current)];setHistoryCount(history.current.length);rebuild.current?.({...initial,nodes:[]});setMessage("Original shape restored in draft.");}}>Reset sculpt</button></div></div>
    <p role="status" key={revision}>{message}</p>{error&&<p role="alert">{error}</p>}<div className="sculpt-actions"><button onClick={onClose}>Cancel</button><button className="primary" disabled={!changed||!!error} onClick={()=>{if(onApply(fields.current.nodes.length?structuredClone(fields.current):undefined,scene.revision))onClose();else setError("Shape could not be applied. The scene may have changed; cancel and reopen the object.");}}>Apply shape</button></div>
  </DialogContent></Dialog>;
}
